name: Sync Garmin CN to Garmin Global

on:
  workflow_dispatch:
  schedule:
    # 每6小时运行一次（UTC）
    - cron: "0 */6 * * *"

env:
  RQ_COOKIE: ${{ secrets.RQ_COOKIE }}
  RQ_CSRF_TOKEN: ${{ secrets.RQ_CSRF_TOKEN }}
  RQ_USERID: ${{ secrets.RQ_USERID }}
  GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
  GOOGLE_API_CLIENT_EMAIL: ${{ secrets.GOOGLE_API_CLIENT_EMAIL }}
  GOOGLE_API_PRIVATE_KEY: ${{ secrets.GOOGLE_API_PRIVATE_KEY }}
  BARK_KEY: ${{ secrets.BARK_KEY }}
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sync Garmin CN to Garmin Global
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Sync Garmin CN to Garmin Global
        run: yarn sync_cn
        timeout-minutes: 5

      - name: Auto commit if changed
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Save Garmin Session
